FORMAT: 1A

# Three Headed Dragon
    
Three Headed dragon is an api for managing users and their character data

# Group Feat Collection
## /feats{?characterId}
A Feats array with objects

+ Parameters
    + characterId (required, string, `59f8a9b0-3df2-11ea-ba54-ab58c1fd0974`) - Character id

### Retrieve Feats[GET]
Get all the feats from character

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id": "1421ed80-3ed7-11ea-a1d6-6bfe258ce555",
                "featName": "Feat Name",
                "featDescription": "Feat Description",
                "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
            }
        ]

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

## /feats
### Create Feat[POST]
Create a new feat
+ Request (application/json; charset=utf-8)

        {
            "id": "4421ed80-3ed7-11ea-a1d6-6bfe258ce555",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

+ Response 201 (application/json; charset=utf-8)

        {
            "id": "4421ed80-3ed7-11ea-a1d6-6bfe258ce555",
            "featName": "",
            "featDescription": "",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

## /feats/{id}

+ Parameters
    + id (required, string, `1421ed80-3ed7-11ea-a1d6-6bfe258ce555`) - Character id

### Update Feat[PUT]
Update a Feat

+ Request (application/json; charset=utf-8)

        {
            "id": "1421ed80-3ed7-11ea-a1d6-6bfe258ce555",
            "featName": "Feat Namea",
            "featDescription": "Feat Desc",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "1421ed80-3ed7-11ea-a1d6-6bfe258ce555",
            "featName": "Feat Namea",
            "featDescription": "Feat Desc",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

## /feats/{id}

+ Parameters
    + id (required, string, `4421ed80-3ed7-11ea-a1d6-6bfe258ce555`) - Character id

### Delete Feat[DELETE]
Delete a Feat

+ Response 204

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

# Group Item Collection
## /items{?characterId}
A Items array with objects

+ Parameters
    + characterId (required, string, `59f8a9b0-3df2-11ea-ba54-ab58c1fd0974`) - Character id

### Retrieve Items[GET]
Get all the Items from character

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id": "ae835445-5f86-4a9a-a27b-17e71b60317d",
                "itemName": "John Doe",
                "itemDescription": "It work oh so well",
                "itemWeight": "3",
                "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"                
            }
        ]

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

## /items
### Create Items[POST]
Create a new Item
+ Request (application/json; charset=utf-8)

        {
            "id": "5421ed80-3ed7-11ea-a1d6-6bfe258ce555",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

+ Response 201 (application/json; charset=utf-8)

        {
            "id": "5421ed80-3ed7-11ea-a1d6-6bfe258ce555",
            "itemName": "",
            "itemDescription": "",
            "itemWeight": "",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

## /items/{id}

+ Parameters
    + id (required, string, `ae835445-5f86-4a9a-a27b-17e71b60317d`) - Character id

### Update Item[PUT]
Update a Item

+ Request (application/json; charset=utf-8)

        {
            "id": "ae835445-5f86-4a9a-a27b-17e71b60317d",
            "itemName": "John Doea",
            "itemDescription": "It work oh so well",
            "itemWeight": "3",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "ae835445-5f86-4a9a-a27b-17e71b60317d",
            "itemName": "John Doea",
            "itemDescription": "It work oh so well",
            "itemWeight": "3",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

## /items/{id}

+ Parameters
    + id (required, string, `5421ed80-3ed7-11ea-a1d6-6bfe258ce555`) - Character id

### Delete Item[DELETE]
Delete a Item

+ Response 204

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

# Group Skill Collection
## /skills{?characterId}
A Skills array with objects

+ Parameters
    + characterId (required, string, `59f8a9b0-3df2-11ea-ba54-ab58c1fd0974`) - Character id

### Retrieve Skills[GET]
Get all the Skills from character

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id": "3e836f45-6f21-4a9a-a27b-17e71b60317d",
                "skillName": "Run",
                "skillModType": "Dex",
                "skillTotal": "6",
                "skillAbilityMod": "3",
                "skillRank": "3",
                "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"             
            }
        ]

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

## /skills
### Create Skill[POST]
Create a new Skill
+ Request (application/json; charset=utf-8)

        {
            "id": "5421ed80-3ed7-11ea-a1d6-6bfe258ce555",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

+ Response 201 (application/json; charset=utf-8)

        {
            "id": "5421ed80-3ed7-11ea-a1d6-6bfe258ce555",
            "skillName": "",
            "skillModType": "",
            "skillTotal": "",
            "skillAbilityMod": "",
            "skillRank": "",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974" 
        }

## /skills/{id}

+ Parameters
    + id (required, string, `3e836f45-6f21-4a9a-a27b-17e71b60317d`) - Character id

### Update Skill[PUT]
Update a Skill

+ Request (application/json; charset=utf-8)

        {
            "id": "3e836f45-6f21-4a9a-a27b-17e71b60317d",
            "skillName": "Runa",
            "skillModType": "Dex",
            "skillTotal": "6",
            "skillAbilityMod": "3",
            "skillRank": "3",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"  
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "3e836f45-6f21-4a9a-a27b-17e71b60317d",
            "skillName": "Runa",
            "skillModType": "Dex",
            "skillTotal": "6",
            "skillAbilityMod": "3",
            "skillRank": "3",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"  
        }

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

## /skills/{id}

+ Parameters
    + id (required, string, `5421ed80-3ed7-11ea-a1d6-6bfe258ce555`) - Character id

### Delete Skill[DELETE]
Delete a Skill

+ Response 204

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

# Group Spells Collection
## /spells{?characterId}
A Spells array with objects

+ Parameters
    + characterId (required, string, `59f8a9b0-3df2-11ea-ba54-ab58c1fd0974`) - Character id

### Retrieve Skills[GET]
Get all the Skills from character

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id": "62136f45-5f86-229a-a27b-17e71b60317d",
                "spellName": "Fireball",
                "spellComponents": "None",
                "spellCastingTime": "3 seconds",
                "spellRange": "30ft",
                "spellTarget": "AOE",
                "spellDuration": "instant",
                "spellSavingThrow": "Con",
                "spellDescription": "Big booma kabooma",
                "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"      
            }
        ]

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

## /spells
### Create Spells[POST]
Create a new Spells
+ Request (application/json; charset=utf-8)

        {
            "id": "5421ed80-3ed7-11ea-a1d6-6bfe258ce555",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

+ Response 201 (application/json; charset=utf-8)

        {
            "id": "5421ed80-3ed7-11ea-a1d6-6bfe258ce555",
            "spellName": "",
            "spellComponents": "",
            "spellCastingTime": "",
            "spellRange": "",
            "spellTarget": "",
            "spellDuration": "",
            "spellSavingThrow": "",
            "spellDescription": "",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"  
        }

## /spells/{id}

+ Parameters
    + id (required, string, `62136f45-5f86-229a-a27b-17e71b60317d`) - Character id

### Update Spell[PUT]
Update a Spell

+ Request (application/json; charset=utf-8)

        {
            "id": "62136f45-5f86-229a-a27b-17e71b60317d",
            "spellName": "Fireballa",
            "spellComponents": "None",
            "spellCastingTime": "3 seconds",
            "spellRange": "30ft",
            "spellTarget": "AOE",
            "spellDuration": "instant",
            "spellSavingThrow": "Con",
            "spellDescription": "Big booma kabooma",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"  
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "62136f45-5f86-229a-a27b-17e71b60317d",
            "spellName": "Fireballa",
            "spellComponents": "None",
            "spellCastingTime": "3 seconds",
            "spellRange": "30ft",
            "spellTarget": "AOE",
            "spellDuration": "instant",
            "spellSavingThrow": "Con",
            "spellDescription": "Big booma kabooma",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"  
        }

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

## /spells/{id}

+ Parameters
    + id (required, string, `5421ed80-3ed7-11ea-a1d6-6bfe258ce555`) - Character id

### Delete Spell[DELETE]
Delete a Spell

+ Response 204

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }


# Group Weapons Collection
## /weapons{?characterId}
A Weapons array with objects

+ Parameters
    + characterId (required, string, `59f8a9b0-3df2-11ea-ba54-ab58c1fd0974`) - Character id

### Retrieve Weapons[GET]
Get all the Weapons from character

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id": "5e836f4a-5f86-4a9a-a27b-17e71b60317d",
                "weaponName": "Kill Death",
                "weaponAttackBonus": "3",
                "weaponDamage": "d20",
                "weaponCritical": "15-20",
                "weaponRange": "10ft",
                "weaponSpecial": "Its awesome",
                "weaponAmmunition": "None",
                "weaponWeight": "5 pounds",
                "weaponSize": "Large",
                "weaponType": "Slashing",
                "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
            }
        ]

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

## /weapons
### Create Weapons[POST]
Create a new Weapons
+ Request (application/json; charset=utf-8)

        {
            "id": "5421ed80-3ed7-11ea-a1d6-6bfe258ce555",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

+ Response 201 (application/json; charset=utf-8)

        {
            "id": "5421ed80-3ed7-11ea-a1d6-6bfe258ce555",
            "weaponName": "",
            "weaponAttackBonus": "",
            "weaponDamage": "",
            "weaponCritical": "",
            "weaponRange": "",
            "weaponSpecial": "",
            "weaponAmmunition": "",
            "weaponWeight": "",
            "weaponSize": "",
            "weaponType": "",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

## /weapons/{id}

+ Parameters
    + id (required, string, `5e836f4a-5f86-4a9a-a27b-17e71b60317d`) - Character id

### Update Weapon[PUT]
Update a Weapon

+ Request (application/json; charset=utf-8)

        {
            "id": "5e836f4a-5f86-4a9a-a27b-17e71b60317d",
            "weaponName": "Kill Deatha",
            "weaponAttackBonus": "3",
            "weaponDamage": "d20",
            "weaponCritical": "15-20",
            "weaponRange": "10ft",
            "weaponSpecial": "Its awesome",
            "weaponAmmunition": "None",
            "weaponWeight": "5 pounds",
            "weaponSize": "Large",
            "weaponType": "Slashing",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "5e836f4a-5f86-4a9a-a27b-17e71b60317d",
            "weaponName": "Kill Deatha",
            "weaponAttackBonus": "3",
            "weaponDamage": "d20",
            "weaponCritical": "15-20",
            "weaponRange": "10ft",
            "weaponSpecial": "Its awesome",
            "weaponAmmunition": "None",
            "weaponWeight": "5 pounds",
            "weaponSize": "Large",
            "weaponType": "Slashing",
            "characterId": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974"
        }

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }
        
## /weapons/{id}

+ Parameters
    + id (required, string, `5421ed80-3ed7-11ea-a1d6-6bfe258ce555`) - Character id

### Delete Weapon[DELETE]
Delete a Weapon

+ Response 204

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

# Group Authentication

## /login
### POST
Log a user in
+ Request (application/json; charset=utf-8)

    + Body
    
            {
                "username": "test",
                "password": "test"
            }

+ Response 200 (application/json; charset=utf-8)

        {
            "loggedInState": true
        }
        

+ Response 422 (application/json; charset=utf-8)

        {
            "message": "Incorrect username / loggin"
        }
    
# Group Characters Collection

## /characters
A Characters array with objects

### Retrieve Characters[GET]
Get all the Characters from character

+ Response 200 (application/json; charset=utf-8)

        [
            {
            "id": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974",
            "name": "Jimmy",
            "player": "Dominic",
            "alignment": "Chaotic Good",
            "level": "3",
            "userClass": " Fighter",
            "race": "Human",
            "campaign": "Curse of dog",
            "diety": "Jenny",
            "size": "Medium",
            "age": "12",
            "gender": "Male",
            "hair": "Black",
            "height": "5'2",
            "characterWeight": "120",
            "eyes": "Green",
            "currency": " 10 Plat",
            "languages": "Common",
            "description": "He a real cool dude",
            "personality": "Aaaaa",
            "traits": "Awesome",
            "flaws": "Lazy",
            "contacts": "None",
            "enemies": "Everyone",
            "notes": "Dont forget the pie",
            "image": "henry.jpg",
            "stat": ["1", "1", "1", "1", "1", "1"],
            "statMod": ["2", "2", "2", "2", "2", "2"],
            "hp": "300",
            "hpWounds": "250",
            "hpDice": "10d20",
            "dmgReduction": "None",
            "ac": "20",
            "acArmor": "5",
            "acShield": "5",
            "acDex": "5",
            "acNatural": " 5",
            "acMisc": "0",
            "acTouch": "10",
            "acFlat": "10",
            "init": "12",
            "initDex": "6",
            "initMisc": "6",
            "speed": "20ft",
            "attackTotal": ["3","4"],
            "attackBase": ["3","4"],
            "attackMod": ["3","4"],
            "attackMisc": ["3","4"],
            "spellsKnown": ["3","4","3","4","3","4","3","4","3","4"],
            "spellsPerDay": ["3","4","3","4","3","4","3","4","3","4"],
            "spellDC": ["3","4","3","4","3","4","3","4","3","4"],
            "savingThrow": ["1","2","3"],
            "savingThrowBase": ["1","2","3"],
            "savingThrowMod": ["1","2","3"],
            "weight": ["1","2","3","4","5"],
            "userId": "41236f45-5f86-4a9a-a27b-17e71b60317d"
            }
        ]

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

## /characters
### Create Character[POST]
Create a new Character
+ Request (application/json; charset=utf-8)

        {
            "id": "5421ed80-3ed7-11ea-a1d6-6bfe258ce555"
        }

+ Response 201 (application/json; charset=utf-8)

        {
            "id": "5421ed80-3ed7-11ea-a1d6-6bfe258ce555",
            "name": "",
            "player": "",
            "alignment": "",
            "level": "",
            "userClass": " ",
            "race": "",
            "campaign": "",
            "diety": "",
            "size": "",
            "age": "",
            "gender": "",
            "hair": "",
            "height": "",
            "characterWeight": "",
            "eyes": "",
            "currency": "",
            "languages": "",
            "description": "",
            "personality": "",
            "traits": "",
            "flaws": "",
            "contacts": "",
            "enemies": "",
            "notes": "",
            "image": "henry.jpg",
            "stat": ["", "", "", "", "", ""],
            "statMod": ["", "", "", "", "", ""],
            "hp": "",
            "hpWounds": "",
            "hpDice": "",
            "dmgReduction": "",
            "ac": "",
            "acArmor": "",
            "acShield": "",
            "acDex": "",
            "acNatural": "",
            "acMisc": "",
            "acTouch": "",
            "acFlat": "",
            "init": "",
            "initDex": "",
            "initMisc": "",
            "speed": "",
            "attackTotal": ["", ""],
            "attackBase": ["", ""],
            "attackMod": ["", ""],
            "attackMisc": ["", ""],
            "spellsKnown": ["", "", "", "", "", "", "", "", "", ""],
            "spellsPerDay": ["", "", "", "", "", "", "", "", "", ""],
            "spellDC": ["", "", "", "", "", "", "", "", "", ""],
            "savingThrow": ["", "", ""],
            "savingThrowBase": ["", "", ""],
            "savingThrowMod": ["", "", ""],
            "weight": ["", "", "", "", ""],
            "userId": "41236f45-5f86-4a9a-a27b-17e71b60317d"
        }
        
## /characters/{id}

+ Parameters
    + id (required, string, `59f8a9b0-3df2-11ea-ba54-ab58c1fd0974`) - Character id

### Get a Character[GET]
Get a Character

+ Response 200 (application/json; charset=utf-8)

    + Body

            
            {
                "id": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974",
                "name": "Jimmy",
                "player": "Dominic",
                "alignment": "Chaotic Good",
                "level": "3",
                "userClass": " Fighter",
                "race": "Human",
                "campaign": "Curse of dog",
                "diety": "Jenny",
                "size": "Medium",
                "age": "12",
                "gender": "Male",
                "hair": "Black",
                "height": "5'2",
                "characterWeight": "120",
                "eyes": "Green",
                "currency": " 10 Plat",
                "languages": "Common",
                "description": "He a real cool dude",
                "personality": "Aaaaa",
                "traits": "Awesome",
                "flaws": "Lazy",
                "contacts": "None",
                "enemies": "Everyone",
                "notes": "Dont forget the pie",
                "image": "henry.jpg",
                "stat": ["1", "1", "1", "1", "1", "1"],
                "statMod": ["2", "2", "2", "2", "2", "2"],
                "hp": "300",
                "hpWounds": "250",
                "hpDice": "10d20",
                "dmgReduction": "None",
                "ac": "20",
                "acArmor": "5",
                "acShield": "5",
                "acDex": "5",
                "acNatural": " 5",
                "acMisc": "0",
                "acTouch": "10",
                "acFlat": "10",
                "init": "12",
                "initDex": "6",
                "initMisc": "6",
                "speed": "20ft",
                "attackTotal": ["3","4"],
                "attackBase": ["3","4"],
                "attackMod": ["3","4"],
                "attackMisc": ["3","4"],
                "spellsKnown": ["3","4","3","4","3","4","3","4","3","4"],
                "spellsPerDay": ["3","4","3","4","3","4","3","4","3","4"],
                "spellDC": ["3","4","3","4","3","4","3","4","3","4"],
                "savingThrow": ["1","2","3"],
                "savingThrowBase": ["1","2","3"],
                "savingThrowMod": ["1","2","3"],
                "weight": ["1","2","3","4","5"],
                "userId": "41236f45-5f86-4a9a-a27b-17e71b60317d"
            }
            
            
+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }

## /characters/{id}

+ Parameters
    + id (required, string, `59f8a9b0-3df2-11ea-ba54-ab58c1fd0974`) - Character id

### Update Character[PUT]
Update a Character

+ Request (application/json; charset=utf-8)

        {
            "id": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974",
            "name": "Jimmya",
            "player": "Dominic",
            "alignment": "Chaotic Good",
            "level": "3",
            "userClass": " Fighter",
            "race": "Human",
            "campaign": "Curse of dog",
            "diety": "Jenny",
            "size": "Medium",
            "age": "12",
            "gender": "Male",
            "hair": "Black",
            "height": "5'2",
            "characterWeight": "120",
            "eyes": "Green",
            "currency": " 10 Plat",
            "languages": "Common",
            "description": "He a real cool dude",
            "personality": "Aaaaa",
            "traits": "Awesome",
            "flaws": "Lazy",
            "contacts": "None",
            "enemies": "Everyone",
            "notes": "Dont forget the pie",
            "image": "henry.jpg",
            "stat": ["1", "1", "1", "1", "1", "1"],
            "statMod": ["2", "2", "2", "2", "2", "2"],
            "hp": "300",
            "hpWounds": "250",
            "hpDice": "10d20",
            "dmgReduction": "None",
            "ac": "20",
            "acArmor": "5",
            "acShield": "5",
            "acDex": "5",
            "acNatural": " 5",
            "acMisc": "0",
            "acTouch": "10",
            "acFlat": "10",
            "init": "12",
            "initDex": "6",
            "initMisc": "6",
            "speed": "20ft",
            "attackTotal": ["3","4"],
            "attackBase": ["3","4"],
            "attackMod": ["3","4"],
            "attackMisc": ["3","4"],
            "spellsKnown": ["3","4","3","4","3","4","3","4","3","4"],
            "spellsPerDay": ["3","4","3","4","3","4","3","4","3","4"],
            "spellDC": ["3","4","3","4","3","4","3","4","3","4"],
            "savingThrow": ["1","2","3"],
            "savingThrowBase": ["1","2","3"],
            "savingThrowMod": ["1","2","3"],
            "weight": ["1","2","3","4","5"],
            "userId": "41236f45-5f86-4a9a-a27b-17e71b60317d"
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "59f8a9b0-3df2-11ea-ba54-ab58c1fd0974",
            "name": "Jimmya",
            "player": "Dominic",
            "alignment": "Chaotic Good",
            "level": "3",
            "userClass": " Fighter",
            "race": "Human",
            "campaign": "Curse of dog",
            "diety": "Jenny",
            "size": "Medium",
            "age": "12",
            "gender": "Male",
            "hair": "Black",
            "height": "5'2",
            "characterWeight": "120",
            "eyes": "Green",
            "currency": " 10 Plat",
            "languages": "Common",
            "description": "He a real cool dude",
            "personality": "Aaaaa",
            "traits": "Awesome",
            "flaws": "Lazy",
            "contacts": "None",
            "enemies": "Everyone",
            "notes": "Dont forget the pie",
            "image": "henry.jpg",
            "stat": ["1", "1", "1", "1", "1", "1"],
            "statMod": ["2", "2", "2", "2", "2", "2"],
            "hp": "300",
            "hpWounds": "250",
            "hpDice": "10d20",
            "dmgReduction": "None",
            "ac": "20",
            "acArmor": "5",
            "acShield": "5",
            "acDex": "5",
            "acNatural": " 5",
            "acMisc": "0",
            "acTouch": "10",
            "acFlat": "10",
            "init": "12",
            "initDex": "6",
            "initMisc": "6",
            "speed": "20ft",
            "attackTotal": ["3","4"],
            "attackBase": ["3","4"],
            "attackMod": ["3","4"],
            "attackMisc": ["3","4"],
            "spellsKnown": ["3","4","3","4","3","4","3","4","3","4"],
            "spellsPerDay": ["3","4","3","4","3","4","3","4","3","4"],
            "spellDC": ["3","4","3","4","3","4","3","4","3","4"],
            "savingThrow": ["1","2","3"],
            "savingThrowBase": ["1","2","3"],
            "savingThrowMod": ["1","2","3"],
            "weight": ["1","2","3","4","5"],
            "userId": "41236f45-5f86-4a9a-a27b-17e71b60317d"
        }
        

+ Response 422 (application/json; charset=utf-8)

        {
            "error": "Incorrect"
        }

## /characters/{id}

+ Parameters
    + id (required, string, `5421ed80-3ed7-11ea-a1d6-6bfe258ce555`) - Character id

### Delete Character[DELETE]
Delete a Character

+ Response 204

+ Response 401 (application/json; charset=utf-8)

        {
            "error": "error.unauthorized"
        }