export const REQ_SHEETS_PENDING = 'REQ_SHEETS_PENDING';
export const REQ_SHEETS_SUCCESS = 'REQ_SHEETS_SUCCESS';
export const REQ_SHEETS_ERROR = 'REQ_SHEETS_ERROR';

export const REQ_SHEET_PENDING = 'REQ_SHEET_PENDING';
export const REQ_SHEET_SUCCESS = 'REQ_SHEET_SUCCESS';
export const REQ_SHEET_ERROR = 'REQ_SHEET_ERROR';

export const ADD_SHEET_PENDING = 'ADD_SHEETS_PENDING';
export const ADD_SHEET_SUCCESS = 'ADD_SHEETS_SUCCESS';
export const ADD_SHEET_ERROR = 'ADD_SHEETS_ERROR';

export const UPDATE_SHEET_PENDING = 'UPDATE_SHEETS_PENDING';
export const UPDATE_SHEET_SUCCESS = 'UPDATE_SHEETS_SUCCESS';
export const UPDATE_SHEET_ERROR = 'UPDATE_SHEETS_ERROR';

export const DELETE_SHEET_PENDING = 'DELETE_SHEETS_PENDING';
export const DELETE_SHEET_SUCCESS = 'DELETE_SHEETS_SUCCESS';
export const DELETE_SHEET_ERROR = 'DELETE_SHEETS_ERROR';

export const REQ_SKILLS_PENDING = 'REQ_SKILLS_PENDING';
export const REQ_SKILLS_SUCCESS = 'REQ_SKILLS_SUCCESS';
export const REQ_SKILLS_ERROR = 'REQ_SKILLS_ERROR';

export const REQ_SKILL_PENDING = 'REQ_SKILL_PENDING';
export const REQ_SKILL_SUCCESS = 'REQ_SKILL_SUCCESS';
export const REQ_SKILL_ERROR = 'REQ_SKILL_ERROR';

export const ADD_SKILL_PENDING = 'ADD_SKILL_PENDING';
export const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS';
export const ADD_SKILL_ERROR = 'ADD_SKILL_ERROR';

export const UPDATE_SKILL_PENDING = 'UPDATE_SKILL_PENDING';
export const UPDATE_SKILL_SUCCESS = 'UPDATE_SKILL_SUCCESS';
export const UPDATE_SKILL_ERROR = 'UPDATE_SKILL_ERROR';

export const DELETE_SKILL_PENDING = 'DELETE_SKILL_PENDING';
export const DELETE_SKILL_SUCCESS = 'DELETE_SKILL_SUCCESS';
export const DELETE_SKILL_ERROR = 'DELETE_SKILL_ERROR';

export const REQ_FEATS_PENDING = 'REQ_FEATS_PENDING';
export const REQ_FEATS_SUCCESS = 'REQ_FEATS_SUCCESS';
export const REQ_FEATS_ERROR = 'REQ_FEATS_ERROR';

export const REQ_FEAT_PENDING = 'REQ_FEAT_PENDING';
export const REQ_FEAT_SUCCESS = 'REQ_FEAT_SUCCESS';
export const REQ_FEAT_ERROR = 'REQ_FEAT_ERROR';

export const ADD_FEAT_PENDING = 'ADD_FEAT_PENDING';
export const ADD_FEAT_SUCCESS = 'ADD_FEAT_SUCCESS';
export const ADD_FEAT_ERROR = 'ADD_FEAT_ERROR';

export const UPDATE_FEAT_PENDING = 'UPDATE_FEAT_PENDING';
export const UPDATE_FEAT_SUCCESS = 'UPDATE_FEAT_SUCCESS';
export const UPDATE_FEAT_ERROR = 'UPDATE_FEAT_ERROR';

export const DELETE_FEAT_PENDING = 'DELETE_FEAT_PENDING';
export const DELETE_FEAT_SUCCESS = 'DELETE_FEAT_SUCCESS';
export const DELETE_FEAT_ERROR = 'DELETE_FEAT_ERROR';

export const REQ_ITEMS_PENDING = 'REQ_ITEMS_PENDING';
export const REQ_ITEMS_SUCCESS = 'REQ_ITEMS_SUCCESS';
export const REQ_ITEMS_ERROR = 'REQ_ITEMS_ERROR';

export const REQ_ITEM_PENDING = 'REQ_ITEM_PENDING';
export const REQ_ITEM_SUCCESS = 'REQ_ITEM_SUCCESS';
export const REQ_ITEM_ERROR = 'REQ_ITEM_ERROR';

export const ADD_ITEM_PENDING = 'ADD_ITEM_PENDING';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';

export const UPDATE_ITEM_PENDING = 'UPDATE_ITEM_PENDING';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_ERROR = 'UPDATE_ITEM_ERROR';

export const DELETE_ITEM_PENDING = 'DELETE_ITEM_PENDING';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';

export const REQ_SPELLS_PENDING = 'REQ_SPELLS_PENDING';
export const REQ_SPELLS_SUCCESS = 'REQ_SPELLS_SUCCESS';
export const REQ_SPELLS_ERROR = 'REQ_SPELLS_ERROR';

export const REQ_SPELL_PENDING = 'REQ_SPELL_PENDING';
export const REQ_SPELL_SUCCESS = 'REQ_SPELL_SUCCESS';
export const REQ_SPELL_ERROR = 'REQ_SPELL_ERROR';

export const ADD_SPELL_PENDING = 'ADD_SPELL_PENDING';
export const ADD_SPELL_SUCCESS = 'ADD_SPELL_SUCCESS';
export const ADD_SPELL_ERROR = 'ADD_SPELL_ERROR';

export const UPDATE_SPELL_PENDING = 'UPDATE_SPELL_PENDING';
export const UPDATE_SPELL_SUCCESS = 'UPDATE_SPELL_SUCCESS';
export const UPDATE_SPELL_ERROR = 'UPDATE_SPELL_ERROR';

export const DELETE_SPELL_PENDING = 'DELETE_SPELL_PENDING';
export const DELETE_SPELL_SUCCESS = 'DELETE_SPELL_SUCCESS';
export const DELETE_SPELL_ERROR = 'DELETE_SPELL_ERROR';
