export const REQ_SHEETS_PENDING = 'REQ_SHEETS_PENDING';
export const REQ_SHEETS_SUCCESS = 'REQ_SHEETS_SUCCESS';
export const REQ_SHEETS_ERROR = 'REQ_SHEETS_ERROR';

export const ADD_SHEET_PENDING = 'ADD_SHEETS_PENDING';
export const ADD_SHEET_SUCCESS = 'ADD_SHEETS_SUCCESS';
export const ADD_SHEET_ERROR = 'ADD_SHEETS_ERROR';

export const UPDATE_SHEET_PENDING = 'UPDATE_SHEETS_PENDING';
export const UPDATE_SHEET_SUCCESS = 'UPDATE_SHEETS_SUCCESS';
export const UPDATE_SHEET_ERROR = 'UPDATE_SHEETS_ERROR';

export const DELETE_SHEET_PENDING = 'DELETE_SHEETS_PENDING';
export const DELETE_SHEET_SUCCESS = 'DELETE_SHEETS_SUCCESS';
export const DELETE_SHEET_ERROR = 'DELETE_SHEETS_ERROR';
