export const REQ_SHEETS_PENDING = 'REQ_SHEETS_PENDING';
export const REQ_SHEETS_SUCCESS = 'REQ_SHEETS_SUCCESS';
export const REQ_SHEETS_ERROR = 'REQ_SHEETS_ERROR';

export const REQ_SHEET_PENDING = 'REQ_SHEET_PENDING';
export const REQ_SHEET_SUCCESS = 'REQ_SHEET_SUCCESS';
export const REQ_SHEET_ERROR = 'REQ_SHEET_ERROR';

export const ADD_SHEET_PENDING = 'ADD_SHEETS_PENDING';
export const ADD_SHEET_SUCCESS = 'ADD_SHEETS_SUCCESS';
export const ADD_SHEET_ERROR = 'ADD_SHEETS_ERROR';

export const UPDATE_SHEET_PENDING = 'UPDATE_SHEETS_PENDING';
export const UPDATE_SHEET_SUCCESS = 'UPDATE_SHEETS_SUCCESS';
export const UPDATE_SHEET_ERROR = 'UPDATE_SHEETS_ERROR';

export const DELETE_SHEET_PENDING = 'DELETE_SHEETS_PENDING';
export const DELETE_SHEET_SUCCESS = 'DELETE_SHEETS_SUCCESS';
export const DELETE_SHEET_ERROR = 'DELETE_SHEETS_ERROR';

export const REQ_SKILLS_PENDING = 'REQ_SKILLS_PENDING';
export const REQ_SKILLS_SUCCESS = 'REQ_SKILLS_SUCCESS';
export const REQ_SKILLS_ERROR = 'REQ_SKILLS_ERROR';

export const REQ_SKILL_PENDING = 'REQ_SKILL_PENDING';
export const REQ_SKILL_SUCCESS = 'REQ_SKILL_SUCCESS';
export const REQ_SKILL_ERROR = 'REQ_SKILL_ERROR';

export const ADD_SKILL_PENDING = 'ADD_SKILL_PENDING';
export const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS';
export const ADD_SKILL_ERROR = 'ADD_SKILL_ERROR';

export const UPDATE_SKILL_PENDING = 'UPDATE_SKILL_PENDING';
export const UPDATE_SKILL_SUCCESS = 'UPDATE_SKILL_SUCCESS';
export const UPDATE_SKILL_ERROR = 'UPDATE_SKILL_ERROR';

export const DELETE_SKILL_PENDING = 'DELETE_SKILL_PENDING';
export const DELETE_SKILL_SUCCESS = 'DELETE_SKILL_SUCCESS';
export const DELETE_SKILL_ERROR = 'DELETE_SKILL_ERROR';
